# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr = np.arange(10).reshape(2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2 = np.array([[1,1,1,1,1],[1,1,1,1,1]])
print(np.vstack((arr,arr2)))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [4]:
ar = np.array([[0,1,2,3,4],[5,6,7,8,9]])
ar2 = np.array([[1,1,1,1,1],[1,1,1,1,1]])
print(np.hstack((ar,ar2)))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [5]:
array = np.array([[0,1],[2,3],[4,5],[6,7],[8,9]])
print(array.flatten())

[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [13]:
a = np.arange(15).reshape(1,3,5)
print(a)
print("Dimension : ",a.ndim)
a = a.flatten()
print(a)
print("Dimension : ",a.ndim)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
Dimension :  3
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Dimension :  1


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [15]:
b = np.arange(15)
print(b)
print("Dimension : ",b.ndim)
b = b.reshape(5,3)
print(b)
print("Dimension : ",b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Dimension :  1
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Dimension :  2


## Question:7

### Create 5x5 an array and find the square of an array?

In [19]:
aray = np.arange(25).reshape(5,5)
print(aray)
print(np.square(aray))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [21]:
ab = np.arange(30).reshape(5,6)
print(ab)
print("Mean : ",np.mean(ab))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
Mean :  14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [23]:
print("Standard Deviation : ", np.std(ab))

Standard Deviation :  8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [24]:
print("Median : ", np.median(ab))

Median :  14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [28]:
print(ab)
print("\nTranspose : \n", np.transpose(ab))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

Transpose : 
 [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [29]:
abc = np.arange(16).reshape(4,4)
print(abc)
print("Sum of Diagonal elements : ", np.trace(abc))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum of Diagonal elements :  30


## Question:13

### Find the determinant of the previous array in Q12?

In [31]:
print("Determinant : ", np.linalg.det(abc))

-2.9582283945787796e-30


## Question:14

### Find the 5th and 95th percentile of an array?

In [32]:
are = np.array([44,64,22,35,23,76,34,87,35,13,77,54,24,54])
print("5th Percentile : ", np.percentile(are,5))
print("95th Percentile : ", np.percentile(are,95))

5th Percentile :  18.85
95th Percentile :  80.5


## Question:15

### How to find if a given array has any null values?

In [69]:
last = np.array([1,6,0,None,1,None,8])
print(last == None)

[False False False  True False  True False]
