# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [4]:
arr2 = np.arange(10,50,1)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [5]:
np.shape(arr2)

(40,)

5. Print the type of the previous array in question 3

In [6]:
arr2.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [7]:
print("Numpy Version : ",np.__version__)

print("Configuration : ",np.show_config())

Numpy Version :  1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.1

7. Print the dimension of the array in question 3


In [8]:
print(np.ndim(arr2))

1


8. Create a boolean array with all the True values

In [9]:
bool_array = np.ones(10,dtype=bool)
print(bool_array)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [10]:
two_dim = np.array([[1,2,3],[4,5,6]])
print(two_dim)
print("Dimaensions: ",two_dim.ndim)

[[1 2 3]
 [4 5 6]]
Dimaensions:  2


10. Create a three dimensional array



In [11]:
three_dim = np.array([[[22,24,77],[21,88,56],[20,44,55]]])
print(three_dim)
print("Dimaensions: ",three_dim.ndim)

[[[22 24 77]
  [21 88 56]
  [20 44 55]]]
Dimaensions:  3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [12]:
vec = np.arange(10)
print("Vector : ",vec)
print("Reverse Vector : ",vec[::-1])
print("Reverse using built in function : ",np.flipud(vec))

Vector :  [0 1 2 3 4 5 6 7 8 9]
Reverse Vector :  [9 8 7 6 5 4 3 2 1 0]
Reverse using built in function :  [9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [13]:
null = np.zeros(10)
null[4] = 1
null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [14]:
ide = np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [15]:
arr3 = np.array([1, 2, 3, 4, 5])
print(arr3.dtype)
arr3 = arr3.astype('float32')
arr3

int32


array([1., 2., 3., 4., 5.], dtype=float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [16]:
arro = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arri = np.array([[0., 4., 1.],

           [7., 2., 12.]])

arro * arri

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [17]:
arrq = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arrw = np.array([[0., 4., 1.],

            [7., 2., 12.]])

arr4 = (arrq == arrw)
arr4

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [18]:
arra = np.arange(10)
arra2 = arra[arra % 2 == 1]
arra2

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [19]:
arra[arra % 2 == 1] = -1
arra

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [20]:
uarr = np.arange(10)
uarr[5:9] = 12
uarr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [21]:
border = np.ones((6,6))
border[1:-1, 1:-1] = 0
border

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [22]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [24]:
abc = np.arange(10).reshape((5,2))
abc[0]

array([0, 1])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [25]:
abc = np.arange(10).reshape((5,2))
print(abc)
print("Second value of 2nd 1-D Array: ",abc[1][1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Second value of 2nd 1-D Array:  3


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [26]:
aray = np.arange(10).reshape((2,5))
print(aray)
print(aray[:2, 2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
ran = np.random.randint(low=5, high=10, size=(10,10))
mini = ran.min()
maxi = ran.max() 
print("Minimum is : ",mini)
print("Maximum is : ",maxi)

Minimum is :  5
Maximum is :  9


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [29]:
print(np.where(a==b))

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
x = data[names != "Will"]
print(x)

[[-0.08048461  0.28458551 -0.32855501 -0.85153895]
 [ 0.40139931 -0.69300096 -2.37428607  0.08598599]
 [ 0.57227023  1.02511623  0.17547795  0.07777222]
 [-0.96492243 -0.60499965  0.7941848  -1.03023155]
 [-1.24216177  0.67857116  0.88082251  0.21133051]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [6]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
y = data[names != {"Will","Joe"}]
print(y)

[[-0.42483713 -0.10234721 -1.41581223  1.85542901]
 [ 1.44896356  0.63100339 -0.58194777  1.16997495]
 [ 0.05672934 -0.50581068 -0.91284765 -0.17419056]
 [-1.05364232 -0.47803718 -0.79149788  1.17742314]
 [ 0.03991642 -1.06545386 -0.46896334 -1.30119283]
 [ 0.23957434  0.32405024  0.18079395  1.62077642]
 [ 0.39979923 -0.86581471 -0.77513958 -0.8996616 ]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [32]:
dec = np.random.uniform(1,15, size=(5,3))
dec

array([[ 8.63050975,  8.02701953,  6.44207807],
       [13.05417904, 10.86196454, 12.83695767],
       [14.12474689, 11.10665735,  2.28217146],
       [11.31747288,  7.52211397,  2.33877157],
       [ 4.93256521, 12.65313508,  2.10104839]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [4]:
dec1 = np.random.uniform(1,16, size=(2,2,4))
dec1

array([[[15.30774005,  6.00734389,  3.32984122, 10.67352992],
        [ 2.55349956,  1.78735857,  7.70639863,  9.55237521]],

       [[10.37419404,  3.91509844,  2.78600136, 10.99168317],
        [15.07417857, 12.18171087,  8.37656685, 14.18103509]]])

33. Swap axes of the array you created in Question 32

In [15]:
print(np.swapaxes(dec1,1,0))

[[[15.30774005  6.00734389  3.32984122 10.67352992]
  [10.37419404  3.91509844  2.78600136 10.99168317]]

 [[ 2.55349956  1.78735857  7.70639863  9.55237521]
  [15.07417857 12.18171087  8.37656685 14.18103509]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [24]:
sqr = np.array([2,0.2,1,0.5,2,3,0.13,9,4,36])
print(sqr)
print(np.sqrt(sqr))
sqr[sqr < 0.5] = 0
print(sqr)

[ 2.    0.2   1.    0.5   2.    3.    0.13  9.    4.   36.  ]
[1.41421356 0.4472136  1.         0.70710678 1.41421356 1.73205081
 0.36055513 3.         2.         6.        ]
[ 2.   0.   1.   0.5  2.   3.   0.   9.   4.  36. ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [45]:
a1 = np.random.random(12)
a2 = np.random.random(12)
a3 = np.maximum(a1,a2)
print(a1)
print(a2)
print(a3)

[0.00914562 0.105398   0.12897883 0.50015006 0.02720433 0.0982709
 0.41583613 0.66515952 0.18852685 0.39030306 0.90317552 0.95532804]
[0.09411294 0.39829067 0.40583449 0.19140859 0.93102217 0.21528446
 0.08393527 0.18687896 0.42053822 0.43646472 0.46372342 0.5278769 ]
[0.09411294 0.39829067 0.40583449 0.50015006 0.93102217 0.21528446
 0.41583613 0.66515952 0.42053822 0.43646472 0.90317552 0.95532804]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [43]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names2 = np.unique(names)
print(np.sort(names2))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [51]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

result = np.intersect1d(a, b)
print(result)
c = np.where(a == 5)
print(c)
print(np.delete(a,c))

[5]
(array([4], dtype=int64),)
[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [ ]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sp2 = np.delete(sampleArray,2,1)
newColumn = np.array([[10,10,10]])
sp2 = np.append(sp2, newColumn, axis=1)
print(sp2)

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [26]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [25]:
are = np.random.randint(1,20,size=10)
print(are)
print(np.cumsum(are))

[14 18 18 18 15  9 14  7  5 19]
[ 14  32  50  68  83  92 106 113 118 137]
